parameters:
    dbal_configuration:
        dsn: '%env(resolve:DATABASE_URL)%'
        available_drivers:
            mysql: 'pdo_mysql'

    doctrine_migrations:
        ignored_tables:
        table_storage:
            table_name: 'migrations'
        migrations_paths:
            Migrations: '%kernel.project_dir%/migrations'
