version: '3'

services:
    php_fpm:
        container_name: api-php_fpm
        image: php_fpm
        build:
            context: .
            dockerfile: docker/php-8-fpm/prod/Dockerfile

    webserver_nginx:
        container_name: api-webserver_nginx
        image: webserver_nginx
        build:
            context: .
            dockerfile: docker/nginx-1.20/dev/Dockerfile
